include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'example/**' # This line excludes the entire example directory

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    avoid_print: false
